### ISSUE TITLE
Getting blank screen while adding item at 0 position using ArrayFragmentStatePagerAdapter

### ISSUE THREAD

**Issue by vikskod** [takaaki7/ArrayPagerAdapter#3]
At first i was using `ArrayFragmentPagerAdapter` but as you recommended in your **Readme** file i use `ArrayFragmentStatePagerAdapter` because i have huge number of fragment to load. But sometime i am facing **blank screen** while adding item on 0 position. When i swipe on screen blank screen again disappears. I am trying to get cause of that black screen problem but couldn't get succeed.

Code to add item on 0 position in `ArrayPagerAdapter` Class:

```
public void addToFront(T item) {
        synchronized (lock) {
            items.add(0, identifiedItemFactory.create(item));
        }
        itemPositionChangeChecked = new SparseBooleanArray(this.items.size());
        notifyDataSetChanged();
    }
```

**Comment by takaaki7** [comment]
@viksoffice Thank you for report, I reproduced the problem.
I will investigate and fix it.

**Comment by vikskod** [comment]
Thank you for your reply. It would be great help full if you fix it quickly.

**Comment by takaaki7** [comment]
@viksoffice I fixed it. Feel free to reopen this issue if you have any problem.

**Comment by vikskod** [comment]
Thank you for your response and solution. Now I am not getting blank screen if I add item on index. But when i swipe viewpager i am still getting blank screen on unfixed position. Can i email you? if yes please provide me your email address. 
vparajuli819@gmail.com
